#IP сервера
ipPing = ["192.168.0.1", "1.1.1.1"]
#Значение пинга от которого будет ругаться
maxPing = 1
#Сколько раз нужен плохой пинг чтобы пришло увидомление
warningPing = 5
#После N раз появиться сообщение что машина сдохла, это когда TimeOut
downCar = 5
#После N раз появиться сообщение что машина ожила, это когда TimeOut
aliveCar = 8

#Включить увидомление в telegram
switchTelegram = true
#Ключ телеграм бота
telegramBotKey = ""
#ID чата где находиться бот
chatID = ""

#Включить увидомление в Discord
SwitchDiscord = false
#WebHook Url
DiscordWebHook = ""